function toggleSection(event) {
  const chevron = event.currentTarget;
  const subsectionBody = chevron.parentElement.nextElementSibling;
  const subsection = subsectionBody.parentElement

  chevron.style.transform = chevron.style.transform === 'rotate(180deg)' ? 'rotate(0deg)' : 'rotate(180deg)';

  subsectionBody.classList.toggle('expanded');
  subsection.classList.toggle('expanded')
}


function switchContent(id) {

  const [iframeURL, vizURL, author, inspoURL, inspoCaption, inspoText, purposeText, instructionsText, methodologyText] = vizRefs[id];

  document.querySelector('#viz-embed').src = iframeURL
  document.querySelector('#author').innerHTML = "Created by " + author
  document.querySelector('#newtab').href = vizURL
  document.querySelector('#inspo-embed').src = inspoURL
  document.querySelector('.inspo-embed').load()
  document.querySelector('#inspo-caption').innerHTML = inspoCaption
  document.querySelector('#inspo').innerHTML = inspoText
  document.querySelector('#purpose').innerHTML = purposeText
  document.querySelector('#instructions').innerHTML = instructionsText
  document.querySelector('#methodology-text').innerHTML = methodologyText

  const tabs = document.querySelectorAll('.tab')
  tabs.forEach(tab => {tab.classList.remove('active')})
  document.querySelector("#" + id).classList.add('active')
}


// Site initialization
document.addEventListener('DOMContentLoaded', (event) => {
    
  // expand buttons work
    const chevrons = document.querySelectorAll('.chevron');
    chevrons.forEach(chevron => {
      chevron.addEventListener('click', toggleSection);
    });

    // get the click functionality goin here

    // intialize content
    switchContent('blackSpace')

    // Control behavior of the running title
    const runningHead = document.querySelector('.running-head');
    const titleSection = document.querySelector('.title-section');
    const toggleVisibility = () => {
      const titleRect = titleSection.getBoundingClientRect();
      if (titleRect.bottom < 160) {
        runningHead.classList.add('visible');
      } else {
        runningHead.classList.remove('visible');
      }
    };
    window.addEventListener('scroll', toggleVisibility);
  });


// Data dump for rotating visualization sections:
// [viz_URL, author, inspo_embed, inspo-caption, inspo-text, 
//           purpose-text, instructions, methodology-text]
const vizRefs = {
  'blackSpace':  ['black-space/index.html', 'black-space/index.html',
                  'Arjun Phull',
                  'vids/health.mp4',
                  'Du Bois visualized demographics among Black Philadelphians in engaging and intuitive ways.',
                  'This visualization was inspired by Du Bois’s exploration of differential health data among Black and white Pennsylvanians, which you can see in the YouTube video in this section. Du Bois’s original data visualization explored how death rates differed between Black and white Americans across all age groups, using a color-coded bar chart to illustrate the stark difference. Du Bois also famously mapped Philadelphia’s Seventh Ward, creating a visualization in which he encapsulated spatial, socioeconomic, and demographic data. In his charts, Du Bois thought outside the box, using creative spacing and color coding to redefine the purpose of a bar graph and area chart. His creative thinking inspired me to envision my own data visualization, one that leveraged the breadth of geospatial data with the visual familiarity of a bar graph. What you see in front of you is a 3D map of the state of Pennsylvania, reimagined as a bar graph. Each county is colored on a color scale pulled directly from Du Bois’s visualizations, representing the proportion of Black and African-American populations in each county. The heights of each county correspond to normalized rates of environmentally influenced conditions, including asthma, COPD, and lung cancer. The melding of maps and bar graphs into one cohesive visualization pays homage to Du Bois’s eclectic approach to data visualization.',
                  'This visualization is designed to tie together the differential rates of disease across Pennsylvania and the differential proportions of the Black population in each county. As you explore this interactive data visualization, consider the story that the data is telling. You can move the map around to view it at different angles and really examine the correlation between health condition incidence and the Black population within each county. This may help you answer questions such as, “Are Black people disproportionately affected by these environmentally-driven conditions?” and furthermore, “What institutional factors might be driving that correlation?”',
                  '<p class="ss-text">This visualization is optimized for a desktop/laptop computer and does not currently work on mobile devices. You can select a condition to explore across counties from the menu below the map. Then, you can hover over each county to view the relative incidence rate of the selected condition. You can click and drag to move, zoom, and rotate the map.</p>',
                  'To build this visualization, I imported 3D models of each county in Pennsylvania in .gltf format using a JavaScript library called Three.js. There are 67 counties within Pennsylvania, so this made for a lot of lines of code. Thankfully, I was able to use Python to create a code template that would load each model, and so I used Python to automate the loading of each model. The raw data here came from two sources. The data regarding the Black populations of each county came from the U.S. Census Bureau, and the data regarding environmentally-driven conditions came from the American Lung Association. The Black population data was already in percentage form, so I used Python to create a dictionary that mapped each county to its Black population percentage. For the American Lung Association data, I used a Python library called Pandas to transform the tabular condition incidence data into relevant percentages. I then normalized the data on a scale from 1 to 10, which allowed me to highlight the relative spread of disease incidence. Once my data was transformed, I used Three.js and another JavaScript library called GSAP to animate the heights of each county according to the data regarding the condition selected. To build the color scale across all the counties, I created a JavaScript function that takes a county’s percentage of Black population and returns RGB values that correspond to a color between off-white and brown. I then used Three.js to set the color of each county to the color returned by the function. Lastly, I used HTML and CSS to wrap my data visualization within a web app.'
                ],

  'blackLiterature': ['black-literature/index.html', 'black-literature/index.html',
                      'Arjun Phull',
                      'vids/journalism.mp4',
                      'Du Bois depicted the prevalence of Black-authored works within the late-19th century press in engaging and creative ways.',
                      'This visualization was inspired by Du Bois’s <i>American Negro Newspapers and Periodicals</i>, which you can see in the YouTube video in this section. Du Bois’s original visualization contains a chart that explored the presence and prevalence of African American writers within the press of the late 19th century. In this chart, Du Bois and his team used contrasting colors and a pyramidal shape to illustrate the hierarchy and structure of the Black press. The chart showed a strikingly large number of Black-authored periodicals in circulation at the time—a proportion of the press large enough to pave the way for discourse concerning the budding civil rights movement. In my visualization, I sought to emulate Du Bois’s shape-oriented approach to illustrating the prevalence of Black authorship and journalism. Specifically, I sought to examine the proportion of books written in recent years by Black authors. I used pencils to simulate a bar graph, with each pencil representing the relative proportion of books published by Black authors each year over the past few decades.',
                      'This visualization is designed to highlight the exponential growth of Black authorship over the past few decades. As you explore the interactive data visualization, consider the story that the data is telling. You can hover over each pencil one by one to watch the proportion of Black authorship increase year by year. While doing so, think about what world events might have been occurring during this time period. This may help you answer questions such as, “Why did Black authors see such a large increase in representation?” “What might this trend look like in the future?” and, furthermore, “How can we keep this trend moving in the right direction?”',
                      'This visualization is optimized for a desktop/laptop computer and does not work on mobile devices. You can hover over each pencil to view the relative proportion of books published each year by Black authors versus authors of all races.',
                      'To build this visualization, I imported 3D models of pencils in .gltf format using a JavaScript library called Three.js. In order to properly scale the pencils later, I had to import each pencil in three parts: the tip, the middle, and the eraser. The raw data came from the Cooperative Children’s Book Center at the University of Wisconsin-Madison. It was initially in aggregate form, so I used Python to make it accessible and more easily visualized. I used Python to create a dictionary with each year as a key. I had each year map to the proportion of books published by Black authors during that year. This was really efficient, as it allowed me to retrieve any data point within the original dataset by specifying the year. Once my data was transformed, I used Three.js and another JavaScript library called GSAP to grow and shrink the length of the middle of each pencil according to the data on page load. I then used Three.js to constantly position the tip and the eraser adjacent to the middle of the pencil so that the pencils would remain intact as they grow and shrink. I used Three.js to translate each pencil in the z-direction upon hovering, giving the illusion of rising or popping out of the visualization. Lastly, I used HTML and CSS to wrap my data visualization within a web app.'
                    ],

  'healthIncome': ['health-income/index.html', 'health-income/index.html',
                      'Anuj Gupta',
                      'vids/income.mp4',
                      'Du Bois visualized the earning and spending habits of Black families in creative and engaging ways.',
                      'The inspiration for the content of my visualization titled Health and Income Across Race comes from W. E. B. Du Bois’s data visualization titled Income and Expenditure of 150 Negro Families in Atlanta, GA, USA, which you can see in the YouTube video in this section. Although the most informationally dense graph Du Bois and his team created, Du Bois’s graph still manages to be a visual feast. Du Bois uses concise typography, clear photographs, and bright colors to educate his audience, while the various bar charts highlight the differing budgetary discretions for Black families along class lines. In 1900, a head of household made an average of $1,125 per year and would have been considered “well-to-do” according to Du Bois. With inflation, that would only amount to $33,996.59. As seen in the 3D visualization, according to the U.S. Bureau of Labor Statistics, the 2019 median income seems like a significant improvement for Black heads of household at $44,000—until one considers the median income for comparative whites: $80,602. The median white American in their late fifties had $251,000 more wealth than the median Black American.<br><br>Additionally, in terms of form, I was inspired by a famous visualization called the “Gapminder Map” created by Hans Rosling (see Rosling et al., 2018). In this map, Rosling created an animated 2D visualization with the GDP and life expectancy of all the countries in the world plotted over time. You can view what this looks like by going to <a href="https://youtu.be/BPt8ElTQMIg?si=Mt53PINSryO9W9uY" target="_blank" rel="noopener noreferrer" class="newtab" id="newtab">this link</a> (Gapminder Foundation, 2009). The animation in this visualization shows how the health and financial parameters of countries are correlated and how they change over time, revealing startling insights about global development patterns over the last two centuries. I especially liked how the animation in this visualization shows how, over time, some countries have improved their economic well-being, which has impacted their health outcomes as well, while others who continue to be economically oppressed suffer in terms of health outcomes. The animation helps us see these larger patterns, which would’ve taken several hundred static graphs to convey. Using this as inspiration, I decided to see how health and income for different races in the U.S. has varied over time in my data visualization.',
                      'Over time, I’ve felt that while data science does an excellent job of taking a lot of data and producing illuminating insights, it often lacks rhetorical capacities to move people to use those insights in meaningful ways. This is where digital rhetorical devices like animation and storytelling can come in very handy. In this particular visualization, I wanted to explore how animation could help with making data more meaningful. In this visualization, on the x-axis, you see median family income in dollars for different races in the U.S., and on the y-axis, you see life expectancy for those races. The three different balls—blue, red, and yellow—represent African Americans, white Americans, and all other races, respectively. Through an animation function, you see how this data changes over three decades between 1980 and 2017. Another interesting affordance here is that when one hovers over any of the balls, the specific data for that racial group in that time period appears over it, allowing users to dynamically interact with the data.<br><br>As one starts to engage with this data, startling insights begin to emerge. While for white Americans, both health and income have been steadily increasing over time, for African Americans, both parameters continue to lag behind. As recently as 2017, there is a marked difference between life expectancy and income between African Americans and white Americans. Why do you think that is the case? What do you think this visualization tells us? What ways can you use it? The elements of animation, along with the affordance of letting people see specific data points in time by hovering over them, strive to provide users with a panoramic view of the data while including three dimensions—income, health, and time—in a seemingly two-dimensional figure. Such visualizations can be helpful in the classroom as starting points for political discussions about race, economics, and health. They can also be adapted for public awareness campaigns and in technical reports that seek to advocate for social change.',
                      '<p class="ss-text">There are multiple ways to interact with this visualization.</p> <p class="ss-text">On a computer (desktop or laptop):</p> <p class="ss-text indent">Live view: You can view it either in the frame above within this window itself, or by clicking on the link next to it that says “Open this visualization in a new tab.” This live view will render the visualization on your web browser using JavaScript. The visualization automatically animates with a time ticker at the bottom right, which shows how the data changes over the years. By moving your mouse on any of the circles in the visualization, you can see specific data points about health and income for particular racial groups at a given time.</p>  <p class="ss-text">On a handheld device (tablet or mobile phone):</p> <p class="ss-text indent">The same link will also work on a handheld device but might need resizing based on your screen’s dimensions. If your device has a touch screen, you could potentially zoom in or out by using two fingers.</p> <p class="ss-text indent">All other functions of the visualization will work similarly on the handheld device as on a desktop. The only difference is that to see specific data points, instead of hovering over the circular balls, you will need to click on them using your fingers or a stylus.</p>',
                      'I created this visualization using a JavaScript library called D3.js, which is a very powerful library for creating data visualizations. The inspiration for this came from Rosling et al.’s (2018) famous Gapminder visualization. While I do not have any formal background in JavaScript, given my long-term interest in digital rhetoric, I’ve been taking tutorials on different programming languages like Python. Recently, I started getting interested in D3.js through an online course on Udemy by Adam Janes (2020). In one of the modules for that class, Janes (2020) introduces his audience to Rosling’s Gapminder visualization and provides guidance on how to create such a visualization on their own. I studied Janes’ (2020) code for creating a Gapminder visualization available on GitHub. Then I brainstormed how I could create such a visualization with a different dataset and aesthetic for my purposes.<br><br>I first wrote some pseudocode (logic for computer code written in English) on how I could implement that for the health and income data for races in the U.S., which I acquired from publicly available datasets like the U.S. Census Bureau (2023) and the National Center for Health Statistics (2020). Then I started converting the pseudocode into actual code using documentation for the D3.js library available through Bostock (2023), who is also the creator of the D3.js library. D3.js allows users to create an illusion of animation by helping them create an ‘update function.’ This update function tells JavaScript that we have data values for different states of a graph (e.g., for different times) and we want to show these states one after the other rather than all together. The update function then transitions the visual elements of the graph (like the three balls in this case) from one state to another within the x-axis and y-axis of the canvas at quick, regular intervals, which gives a sense of flow or animation.<br><br>This whole process was very challenging for me to implement and led to lots of errors and bugs. My code is not the most elegant, but it gets the job done. For example, while Janes’ (2020) implementation of the visualization processes data present in a .csv file into a .json format using JavaScript itself, I created the .json file by manually putting all the data in, as I wasn’t able to develop an error-free way to convert .csv into JSON using JavaScript. This is not the most efficient and certainly not scalable for large datasets, but since I consider myself to be a beginner, I am happy that I could still get the job done. To assist me during this entire process, it was very helpful to learn from Eyman’s (2023) experiments with using OpenAI’s ChatGPT for web design. I used ChatGPT to assist me with brainstorming coding ideas and debugging the code that I had written. Any coding suggestions given by ChatGPT were reviewed closely by me and corrected for errors.'
],

  'homeownership': ['homeownership/index.html', 'homeownership/index.html',
                      'Arjun Phull',
                      'vids/income.mp4',
                      'Du Bois visualized the wealth and income of Black families in creative and engaging ways.',
                      'This visualization was inspired by Du Bois’s <i>Income and Expenditure of 150 Negro Families in Atlanta, GA, USA</i>, which you can see in the YouTube video in this section. Du Bois’s original visualization was a chart that broke down the average income and spending habits of Black families across the socioeconomic spectrum. In his chart, Du Bois and his team explored the stratification of Black wealth, enumerating the categories on which Black families in varying wealth brackets spent their money. This chart provided commentary on Black homeownership by pointing out which income brackets spent the most and the least on rent. Du Bois also explored the idea of Black land ownership in another of his visualizations, <i>Valuation of Town and City Property Owned By Georgia Negroes</i>. In this chart, a line graph highlights the growth in Black land ownership over the late 19th century and situates this changing data within historical context.<br><br>In envisioning my visualization, I wanted to highlight the dynamic, multicolored approach that Du Bois took in his charts. I used different colored homes arranged in a neighborhood to illustrate changing rates of homeownership across races. The colors of each home were selected from Du Bois’s original color palette, in homage to the distinctive style that he maintained throughout his work. The size of each home changes over time, reflecting the functionality of a bar chart within a much more engaging form factor.',
                      'This visualization is designed to highlight the comparative growth of homeownership across race over the past few decades. As you explore this interactive data visualization, consider the story that the data is telling. You can move the neighborhood around to view it at different angles and really examine the spatial differences in size of each of the houses. This may help you answer questions such as, “Which groups have seen homeownership steadily grow over time?” “Which groups have seen faster or slower growth than others?” and, furthermore, “What institutional factors might be driving these differences?”',
                      'This visualization is optimized for a desktop/laptop computer and does not work on mobile devices. You can click and drag to rotate the neighborhood, or scroll to zoom in or out. You can move the slider to change the current year, allowing you to explore how homeownership rates change over time.',
                      'To build this visualization, I imported 3D models of each house in .gltf format using a JavaScript library called Three.js. I also designed a custom 3D model for the cul-de-sac. The raw data for this model came from the U.S. Census Bureau in percentage form. I used Python to import the data as a CSV. Then, I created a dictionary with each race as a key. Within that dictionary, each race mapped to its own dictionary. Within those inner dictionaries, I had each year map to that race’s percentage of homeownership during that year. This was really useful because it allowed me to get any data point within the original dataset just by specifying two parameters: the race and the year. Once I had workable values, I used Three.js and another JavaScript library called GSAP to read the input of the slider and then grow or shrink the scale of each house according to the data. Lastly, I used HTML and CSS to wrap my data visualization within a web app.'
                    ],

  'familyDynamics': ['family-dynamics/index.html', 'family-dynamics/index.html',
                      'Duo Bao',
                      'vids/family.mp4',
                      'Du Bois visualized demographics among Black Philadelphians in engaging and intuitive ways.',
                      'This project was inspired by an in-depth analysis of existing data management systems for children in foster care, which found that fragmented and inaccessible data was one of the major barriers preventing social workers and policymakers from improving the foster care system. The complexity of the foster care system requires a high degree of transparency and immediate availability of data to better understand the distribution of children in foster care, their needs, and the effectiveness of services. To engage with this problem, we decided to use advanced technical means, such as geographic information systems (GIS) and programming techniques, to create a prototype for an intuitive data visualization platform. The goal of this prototype is to aggregate state foster care child data and present it in an easy-to-understand manner to facilitate data comparison and analysis across state and national levels.',
                      'This project aims to improve public and professional visualization and understanding of U.S. foster care child statistics through maps and interactive tools. We are particularly focused on increasing the transparency and accessibility of data so that policymakers and social service providers can make decisions based on accurate and timely information. By integrating Mapbox and Python technologies, the project converts complex statistical data into easy-to-interpret geographical visualizations, which improves the accessibility of information and also enhances the educational value of the data. Additionally, this combination of technologies has the potential to inspire social action and policy improvements, prompting greater attention to the well-being of children in foster care. The historical roots of racial inequality in the foster care system and its ongoing impact can be revealed using such visualizations in an accessible and effective manner. Each data point on the map tells a story, and together they paint a historical picture of courage, resilience, and hope. By raising public awareness of this issue, we hope to stimulate wider social discussion and drive effective policy change to safeguard all children.',
                      '<p class="ss-text">There are multiple ways to interact with this visualization.</p> <p class="ss-text">On a computer (desktop or laptop):</p> <p class="ss-text indent">Each state on the map is marked with a pin. Users can click on the pins to bring up an information window with specific data on children in foster care in the state. This window provides the number of children in foster care in the state, their age distribution, and other important statistics.</p> <p class="ss-text indent">When the user moves the mouse on the map, the corresponding state will be highlighted, clearly indicating which state the user is currently viewing. This immediate visual feedback helps users intuitively identify and navigate areas of the data that interest them.</p> <p class="ss-text indent">The map is not limited to a flat view, but also provides a rotating interactive globe, allowing users to view the data from different angles. This three-dimensional view can help users better understand the distribution of data across the country.</p> <p class="ss-text">On a handheld device (tablet or mobile phone):</p> <p class="ss-text indent">On mobile devices, users can use common touch screen gestures, such as pinching with two fingers to zoom in and out of the map or rotating two fingers to change the viewing angle. This intuitive and interactive approach makes it extremely easy to explore and share data in different environments.</p> <p class="ss-text indent">When viewing data for a specific state, users can also leverage their mobile device’s sharing capabilities to quickly share foster care statistics with colleagues or social media to promote public discussion and awareness.</p>',
                      'The technical implementation of the project is based on two core technologies: Mapbox and Python. First, we collected data on foster children in each state through official channels and public databases, including information on age, gender, race, and geographic location. Next, we used Python for data cleaning and preprocessing, such as removing duplicates, filling missing values, and converting data formats. The cleaned data was uploaded to the Mapbox platform, and we built an interactive map based on it. Through scripts written in Python, we added a variety of interactive features such as data filtering, region highlighting, and detailed information display, making the final visualization intuitive and feature-rich. In addition, we also used OpenAI’s ChatGPT to assist in solving problems encountered in programming, thus improving development efficiency and code quality.'
                    ],

  'illiteracy': ['https://8th.io/3h7mn', 'https://8th.io/3h7mn',
                      'Anuj Gupta',
                      'vids/education.mp4',
                      'Du Bois visualized the rapid decrease in illiteracy rates among Black Americans throughout the Reconstruction era.',
                      'The inspiration for this visualization comes from an atypical black-and-white bar diagram titled <i>Illiteracy</i> created by W. E. B. Du Bois. His visualization, which is visible in the YouTube video in this section, documents the rather rapid decrease in the number of Black Americans who could not read from Emancipation to the beginning of the 20th century. Just thirty years following the end of slavery, the literacy rate increased by 31.73%. Based on the previous data, Du Bois and his team estimated that Black Americans would achieve 50% literacy by 1900 and represented this guess by incorporating question marks adjacent to the data. The realized data from the National Assessment of Adult Literacy determined the literacy rates for Black Americans actually fared better than their Atlanta University team imagined, with 55.5% of Black people older than 14 years of age learning to read in 1900. As of 1979, less than 1.6% of Black Americans were believed to be illiterate. Despite this perceived progress, the U.S. Department of Education’s National Assessment of Educational Progress reported in 2019 that an astounding 85% of Black American students lack proficiency in reading skills. Additionally, 84% of these same students also struggle to show proficiency in math.',
                      'Data science is very powerful on its own. But when you mix three-dimensional (3D) animation and augmented reality (AR) into it, its power increases exponentially, converting insights and patterns in the data into stories that can inspire people to take action in the world. The purpose of the 3D AR data visualization Illiteracy Rates in the U.S. (1860-1979) is to help audiences understand the immense difficulties that African Americans have faced in overcoming illiteracy. In this visualization, you see a 3D bar graph that shows illiteracy rates in the U.S. starting from the 1870s to the 1980s. This gives you a bird’s-eye view of the entire data spread in one go. The data contains 39 bars (13 decades with three data points about racial differences in illiteracy rates each). Representing all of them in a single 2D graph frame would’ve made for a very cluttered experience. The bird’s-eye view provided in a 3D bar graph makes it easier for us to visualize bigger datasets in one frame. As the visualization shows, in the 1870s, White Americans had a low illiteracy rate of 11.5%, but African Americans, who have historically been denied access to education in the U.S., started with a staggeringly high illiteracy rate of 79%. The visualization emphasizes how much more difficult their struggle to overcome these inequalities has been when compared to other racial groups in the U.S. Apart from its 3D elements, the augmented reality functions add additional potential. Using that functionality, you can project this visualization in your classrooms or at any other setting. For example, it could be projected on public buildings or other social settings related to the world of education to make a rhetorical argument about the connections between literacy and race.',
                      '<p class="ss-text">There are multiple ways to interact with this visualization.</p> <p class="ss-text">On a computer (desktop or laptop):</p> <p class="ss-text indent">Live view: You can view it either in the frame above within this window itself, or by clicking on the link next to it to open the visualization in a new window. This live view will render the visualization through the 8th Wall app. Using your computer’s mouse or trackpad, you can zoom in or out of the visualization. By clicking the circular button at the bottom, you can also take a photo or video.</p>  <p class="ss-text">On a handheld device (tablet or mobile phone):</p> <p class="ss-text indent">To open it on your handheld device, which is the most optimal way to project an AR visualization onto your surroundings, you can use the URL below:</p> <p class="ss-text indent">8th.io/3h7mn</p> <p class="ss-text indent">You will need to grant camera and microphone permissions to 8th Wall to view the visualization.</p> <p class="ss-text indent">The visualization should now be projected in your surroundings in your device’s camera view. Using this functionality, you can project this visualization in your classrooms or at any other setting.</p> <p class="ss-text indent">Using two fingers, you can now rotate the visualization and zoom in or out of it.</p> <p class="ss-text indent">Using the camera button at the bottom, you can click photos or make videos with the visualization projected in your surroundings.</p>',
                      'I created this visualization using an app called 8th Wall, which allows users to create AR experiences. This app has pre-made templates that can be customized even with a limited or no understanding of computer coding. Users who have some understanding of coding, especially in the language called JavaScript, can create more sophisticated and customized visualizations. For this particular visualization, I used a JavaScript library called “aframe” within 8th Wall, which is very helpful for creating 3D visualizations. Using this library, I created box shapes for each data point in the dataset and then arranged them along the x, y, and z axes. The data was adapted from publicly available data about illiteracy rates in the U.S. from the National Center for Education Statistics (1992). Then, using built-in templates in the 8th Wall app, I added AR functionalities so that users can use phone or tablet devices to project this visualization in their environments. They can also click photos or videos of the visualization and share it on social media. Since my own coding literacy is developing, I was very thankful for the detailed documentation provided by the 8th Wall developer community (8th Wall Inc., 2022b; 8th Wall Inc., 2022c). Additionally, taking inspiration from Eyman’s (2023) experiments with using OpenAI’s ChatGPT for web design, I also used ChatGPT to assist me with brainstorming coding ideas and debugging the code that I had written. Any coding suggestions given by ChatGPT were reviewed closely by me and corrected for errors.'
                    ],

  'incarceration': ['incarceration/index.html', 'https://8th.io/j6r6e',
                      'Anuj Gupta',
                      'vids/crime.mp4',
                      'Du Bois visualized the convictions of over 3000 Black prisoners in unconventional, engaging ways.',
                      'The inspiration for my visualization titled <i>Incarceration Across Race</i> comes partially from Du Bois and his team\'s analysis of the convictions of 3,250 African American prisoners. Although their diagram (which is visible in the YouTube video linked in this section) is visually similar to a bar graph, it is actually more like an area chart in function. The slanted chart tells the viewer that the lion\'s share of convicted crimes committed by African Americans were against people (marked with the color brown) or property (marked with the color black). Curiously, Du Bois never compared the incarceration rates of Black Americans versus their white counterparts in a visualization, even though he did document the glaring differences between them in table formats in works like <i>The Philadelphia Negro: A Social Study</i> (Du Bois, 2007, p. 168). In our own times, such facts have become ever more entrenched and hard to ignore at the national level in the U.S. Through publicly available prison census data that we accessed, we learned that despite only representing 13.43% of America\'s national population, Black Americans make up 33.6% of the incarcerated population in the U.S. (Zeng, 2022). On the other hand, while white Americans make up 76.3% of the national population, they represent only 49.4% of the prison population (Zeng, 2022). This means that in terms of representational ratios, for every 1% of African Americans in the national population, there are 2.5% in the prison population, while for every 1% of white Americans in the national population, there are only 0.65% in the prison population. Black Americans are thus nearly four times more overrepresented in prisons compared to their white counterparts.<br><br>In terms of the inspiration for the specific form of this visualization, I used the idea of face filters popularized by platforms like Snapchat, where people could project funny features like animal faces and makeup onto their faces while video chatting. While platforms like Snapchat intend such features to afford light-hearted and humorous augmentation of everyday conversations, I wanted to see if similar features could be remixed for making rhetorical arguments.',
                      'Data is not really useful unless you integrate storytelling and interactivity into it. I\'ve realized that we need to create experiences where people can interact and immerse themselves with the data, which can then rhetorically inspire them to take action. This is a great potential for STEM and humanities scholars to come together to create such experiences. In this visualization, my purpose was to create something that would help people to understand that statistics about social inequities are not just external or distant facts out there in the world, but that they are a part of us and often we are complicit in them. In this augmented reality (AR) visualization, you see two pie charts that get superimposed on users\' faces. The two pie charts consist of two types of populations in the U.S. in 2021. The outer pie chart consists of the national population for different racial groups, while the inner pie chart consists of the prison population for those groups. Each colored ring in the two pie charts represents a particular racial group. Despite only representing 13.43% of America\'s national population, Black Americans make up 33.6% of the incarcerated population in the U.S. (Zeng, 2022). On the other hand, while white Americans make up 76.3% of the national population, they represent only 49.4% of the prison population (Zeng, 2022). This means that in terms of representational ratios, for every 1% of African Americans in the national population, there are 2.5% in the prison population, while for every 1% of white Americans in the national population, there are only 0.65% in the prison population. Black Americans are thus nearly four times more overrepresented in prisons compared to their white counterparts.<br><br>The specific form of this visualization seeks to serve three rhetorical purposes. First, by concatenating proportions of national and prison populations of different racial groups in the U.S. in the form of concentric circles, it seeks to make the concept of representational ratios—which is an important concept in understanding how social inequities work—more accessible and comprehensible to the general population. By contrasting the sizes of the different rings in the pie charts for each racial group, users can make inferences about the data. Second, by projecting these pie charts directly onto users\' faces, the visualization seeks to drive home the point that these statistics are not out there in a distant world, but we are very much a part of them. Thirdly, by providing users with the ability to take photos and videos and circulate them on social media, the visualization provides affordances for such multimodal work to have greater rhetorical velocity (Ridolfo and Devoss, 2009), facilitating its circulation and adaptation across multiple social media contexts.',
                      '<p class="ss-text">There are multiple ways to interact with this visualization.</p> <p class="ss-text">On a computer (desktop or laptop):</p> <p class="ss-text indent">Live view: You can click on the link below the video to open the visualization in a new window. You will need to grant camera and microphone permissions to the 8th Wall app to view the visualization. This live view will render the visualization through the 8th Wall app. Using your computer’s mouse or trackpad, you can then zoom in or out of the visualization. By clicking the circular button at the bottom, you can also take a photo or video and share it on social media.</p>  <p class="ss-text">On a handheld device (tablet or mobile phone):</p> <p class="ss-text indent">To open it on your handheld device, you can go to the URL below:</p> <p class="ss-text indent">8th.io/j6r6e</p> <p class="ss-text indent">You will need to grant camera and microphone permissions to the 8th Wall app to view the visualization.</p> <p class="ss-text indent">The visualization should now be projected on your face using your device’s front camera view. As you move your face, the visualization will move with you.</p> <p class="ss-text indent">Using the camera button at the bottom, you can click photos or make videos with the visualization projected in your surroundings. You can also share it on social media.</p>',
                      'I created this using an app called 8th Wall, which allows users to create AR experiences. This app has pre-made templates that can be customized even with limited or no understanding of computer coding. Users who have some understanding of coding, especially in the language called JavaScript, can create more sophisticated and customized visualizations. For this particular visualization, I used a built-in template for creating face effects in 8th Wall that uses a JavaScript library called “aframe” (8th Wall Inc., 2022a). This template provides a basic framework for creating visual elements that can be projected on users’ faces. How this works is that the 8th Wall engine analyzes facial features using users’ front cameras. As it recognizes the users’ noses, it uses that as its anchor point and then arranges visual elements around that, which can be tweaked and refined by developers. I used aframe’s built-in shape features to create multiple rings that would give the appearance of the two pie charts in the visualization. It took several hours of trial and error to get the distances and ratios right to match the data that I wanted to represent. I used prison data that was publicly available from Zeng (2022) and national population data from the U.S. Census Bureau (2022). Since my own coding literacy is developing, I was very thankful for the detailed documentation provided by the 8th Wall developer community (8th Wall Inc., 2022a). Additionally, taking inspiration from Eyman’s (2023) experiments with using OpenAI’s ChatGPT for web design, I also used ChatGPT to assist me with brainstorming coding ideas and debugging the code that I had written. Any coding suggestions given by ChatGPT were reviewed closely by me and corrected for errors.'
                    ],
}